#!/bin/sh

# blue-merle LuCI backend for GL-XE3000 (Puli AX)

. /lib/blue-merle/functions.sh

logger -p notice -t blue-merle-libexec "Libexec $1"

if [ "$1" = "read-imei" ]; then
    echo -n "$(READ_IMEI)"

elif [ "$1" = "read-imsi" ]; then
    imsi="$(READ_IMSI)"
    if [ -z "$imsi" ]; then
        echo "No IMSI found" >&2
        exit 1
    fi
    echo -n "$imsi"

elif [ "$1" = "random-imei" ]; then
    if bm_can_write_imei; then
        flock -n /tmp/blue-merle-imei-generate.lock timeout 15 /lib/blue-merle/imei_generate.py --random
        READ_IMEI
    else
        echo "IMEI change not supported on this modem" >&2
        exit 2
    fi

elif [ "$1" = "can-write-imei" ]; then
    if bm_can_write_imei; then
        echo -n "1"
    else
        echo -n "0"
    fi

elif [ "$1" = "shutdown-modem" ]; then
    exec gl_modem -B $BM_MODEM_BUS AT AT+CFUN=4

elif [ "$1" = "shutdown" ]; then
    logger -p notice -t blue-merle-libexec "Shutting down"
    echo -n "Shutting down"
    /sbin/poweroff

else
    echo -n '{"msg":"unknown command"}'
    exit 1
fi
